name: ci-e2e
on:
  push:
    branches: [ dev, master]
  pull_request: 
    branches: [ dev, master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ "chromium", "firefox", "webkit" ]
    steps: 
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.8"

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: update package manager & install python3 environment
        run: |
          sudo pip install poetry
          poetry install --with build

      - name: Install npm dependencies
        run: npm ci

      - name: Install E2E browsers
        working-directory: e2e
        run: npx playwright install ${{ matrix.browser }} --with-deps

      - name: Run E2E tests
        run: poetry run npm run e2e:${{ matrix.browser }}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          OS: linux
