name: Release

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{steps.release.outputs.release_created}}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: python
          token: ${{secrets.GITHUB_TOKEN}}
          command: manifest
